import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans'; // Changed import path
import { Header } from '@/components/ui/Header';
import "./globals.css";

const geistSans = GeistSans; // Remove function call since GeistSans is already a font instance

export const metadata: Metadata = {
  title: "Create Next App", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}