import type { Metadata } from "next";
import { GeistSans } from 'geist/font';
import { Header } from '@/components/ui/Header';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}